# -*- coding: utf-8 -*-
"""NVDA analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3LMj7xRO-5LagVNBiJ9DF5-Z9oC8gVo
"""

import numpy as np
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sympol='NVDA'
sdate='2021-01-01'
edate='2024-12-31'
price=yf.download(sympol,sdate,edate,auto_adjust=False,multi_level_index=False)

price.head()

!pip -q install pandas_ta

"""#SIMPLE MOVING AVERAGE (SMA)"""

import pandas_ta as ta
# SMA simple moving average
price['mo50']=ta.sma(price['Adj Close'],50)
price['mo100']=ta.sma(price['Adj Close'],100)
#💡 **Finance logic:** When the current price is **above** the SMA → bullish signal. When **below** → bearish signal.
#Traders also watch for **"Golden Cross"** (mo50 crosses above mo100) as a strong buy signal.

# STDEV Rolling Standard Deviation (Volatility)
price['std5']=ta.stdev(price['Adj Close'],5)
price['std20']=ta.stdev(price['Adj Close'],10)

#**Finance logic:** High std = high risk/volatility. Low std = stable, calm price action.
#This feeds into strategies like **Bollinger Bands**.

price.tail()

price['signal']=np.where(price['Adj Close'].shift(-1)>price['Adj Close'],1,-1)
price.head()

# Data Splitting
price.dropna(inplace=True)
X=price[['mo50','mo100','std5','std20']]
y=price['signal']

display(X.head())
display(y.head())

split=int(len(X)*0.8)
X_train,X_test=X[:split],X[split:]
y_train,y_test=y[:split],y[split:]

# Logistic Regression
from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(X_train,y_train)

y_pred=model_LR.predict(X_test)

display(y_test)
display(y_pred)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

